// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClpgNdymVOgoXQorrESPi_alVxSHZxvvE',
    appId: '1:20774385490:web:ff0ba8321375b75e30ec8b',
    messagingSenderId: '20774385490',
    projectId: 'quranapp-88a8c',
    authDomain: 'quranapp-88a8c.firebaseapp.com',
    storageBucket: 'quranapp-88a8c.appspot.com',
    measurementId: 'G-GHZCF4PH27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAffbmHxkao7w_eMMMNGgUgFlpjeeEX2Fw',
    appId: '1:20774385490:android:99bcbe5fa5fe331830ec8b',
    messagingSenderId: '20774385490',
    projectId: 'quranapp-88a8c',
    storageBucket: 'quranapp-88a8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP9mnoWGuPniZK_IdyWerfCJ2RMkZ_NPU',
    appId: '1:20774385490:ios:c5ad7dcda3007f7130ec8b',
    messagingSenderId: '20774385490',
    projectId: 'quranapp-88a8c',
    storageBucket: 'quranapp-88a8c.appspot.com',
    iosBundleId: 'com.example.quraanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP9mnoWGuPniZK_IdyWerfCJ2RMkZ_NPU',
    appId: '1:20774385490:ios:dee2eb4d6029843a30ec8b',
    messagingSenderId: '20774385490',
    projectId: 'quranapp-88a8c',
    storageBucket: 'quranapp-88a8c.appspot.com',
    iosBundleId: 'com.example.quraanApp.RunnerTests',
  );
}
